### ISSUE TITLE
Making the App Responsive and Look Good on Mobile Devices

### ISSUE THREAD

**Issue by MarcoMorawec** [AndyAbplanalp/Splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by AndyAbplanalp** [comment]
Marco - it looks like adding <meta name="viewport" content="initial-scale=1"> to the <head> tag in application.html.erb worked.  It looks much better on my phone as the text in lower right has been moved up.  Does that work for you as well?

**Comment by MarcoMorawec** [comment]
@AndyAbplanalp :+1: 

Looks like you got it all fixed [with commit](https://github.com/AndyAbplanalp/Splurty/commit/2376bbecef8b9f999c58ed9ba93b86eabfbe0529)

Make sure to close the issue, now that you fixed it :)
