### ISSUE TITLE
Fixing the top-nav

### ISSUE THREAD

**Issue by MarcoMorawec** [AndyAbplanalp/Splurty#2]
In the top navigation it looks like the "contribute" and "about" links are not pulled to the right hand side of the top nav when viewed on desktop.

I have a feeling that this is a CSS class or "span" issue. 

![screen shot 2015-04-07 at 10 59 12 am](https://cloud.githubusercontent.com/assets/1474717/7026010/28588634-dd15-11e4-8149-d5536316fe1e.png)

**Comment by AndyAbplanalp** [comment]
Changed to add 'pull-right' in class and found a missing </div> tag.  Thanks Marco!

    <div class="pull-right col-xs-8 col-xs-offset-1 col-sm-offset-1 col-sm-5 links">
    	
  		<%= link_to 'Contribute', '#', :data => {:toggle => 'modal', :target => '#myModal'} %>
  		&nbsp;&nbsp;
    	<%= link_to 'About', about_path %>

**Comment by MarcoMorawec** [comment]
@AndyAbplanalp I commented directly on your commit. 

Make sure to close the issue, now that it's taken care of.
